Artifacts : artifacts

Data_Ingestion:
  root_dir : artifacts/data_ingestion
  source_dir : DATA_BOOK\CRisk_Analysis.csv
  train_dir : artifacts/data_ingestion/train.csv
  test_dir : artifacts/data_ingestion/test.csv

Data_Transformation:
   transformation_dir : artifacts/data_transformation
   preprocessor_dir : artifacts/data_transformation/preprocessor.pkl

