Artifacts : artifacts

Data_Ingestion:
  root_dir : artifacts/data_ingestion
  source_dir : DATA_BOOK\Rcredit_Anlysis.csv
  train_dir : artifacts/data_ingestion/train.csv
  test_dir : artifacts/data_ingestion/test.csv

Data_Transformation:
   transformation_dir : artifacts/data_transformation
   preprocessor_dir : artifacts/data_transformation/preprocessor.pkl

Model_Trainer:
   trainer_dir  : artifacts/model_trainer
   model_dir  : artifacts/model_trainer/model.pkl

Model_Evaluation :
   model_eval : artifacts/model_evaluation
   updated_model : artifacts/model_update.pkl



